/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./themes/obsidian-flux/layouts/**/*.html",
    "./content/**/*.{md,html}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "primary-fixed-dim": "#ddb7ff",
        "on-tertiary-container": "#00311f",
        tertiary: "#4edea3",
        "inverse-primary": "#842bd2",
        "secondary-container": "#03b5d3",
        "error-container": "#93000a",
        outline: "#988d9f",
        "secondary-fixed": "#acedff",
        "surface-dim": "#131313",
        "on-secondary": "#003640",
        "surface-tint": "#ddb7ff",
        "tertiary-fixed-dim": "#4edea3",
        "on-secondary-fixed": "#001f26",
        "on-tertiary": "#003824",
        "surface-container": "#201f1f",
        "surface-container-highest": "#353534",
        secondary: "#4cd7f6",
        "surface-variant": "#353534",
        "surface-bright": "#3a3939",
        "on-secondary-container": "#00424e",
        "on-primary-fixed": "#2c0051",
        error: "#ffb4ab",
        "on-primary": "#490080",
        "inverse-on-surface": "#313030",
        "on-primary-container": "#400071",
        "surface-container-high": "#2a2a2a",
        "on-tertiary-fixed": "#002113",
        "on-surface": "#e5e2e1",
        "on-error": "#690005",
        "on-tertiary-fixed-variant": "#005236",
        "outline-variant": "#4d4354",
        "surface-container-lowest": "#0e0e0e",
        "on-primary-fixed-variant": "#6900b3",
        background: "#131313",
        "secondary-fixed-dim": "#4cd7f6",
        "primary-container": "#b76dff",
        "primary-fixed": "#f0dbff",
        "on-secondary-fixed-variant": "#004e5c",
        "inverse-surface": "#e5e2e1",
        surface: "#131313",
        "tertiary-container": "#00a572",
        primary: "#ddb7ff",
        "on-surface-variant": "#cfc2d6",
        "surface-container-low": "#1c1b1b",
        "on-background": "#e5e2e1",
        "tertiary-fixed": "#6ffbbe",
        "on-error-container": "#ffdad6",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        "2xl": "1rem",
        full: "0.75rem",
      },
      spacing: {
        xs: "4px",
        gutter: "24px",
        sm: "8px",
        lg: "24px",
        "container-max": "1200px",
        md: "16px",
        xl: "48px",
        "2xl": "80px",
        base: "4px",
      },
      maxWidth: {
        "container-max": "1200px",
      },
      fontFamily: {
        "code-sm": ["Geist", "Vazirmatn", "ui-monospace", "monospace"],
        "body-sm": ["Inter", "Vazirmatn", "system-ui", "sans-serif"],
        "display-hero-mobile": ["Geist", "Vazirmatn", "system-ui", "sans-serif"],
        "body-lg": ["Inter", "Vazirmatn", "system-ui", "sans-serif"],
        "headline-md": ["Geist", "Vazirmatn", "system-ui", "sans-serif"],
        "headline-lg": ["Geist", "Vazirmatn", "system-ui", "sans-serif"],
        "body-md": ["Inter", "Vazirmatn", "system-ui", "sans-serif"],
        "label-caps": ["Geist", "Vazirmatn", "system-ui", "sans-serif"],
        "display-hero": ["Geist", "Vazirmatn", "system-ui", "sans-serif"],
      },
      fontSize: {
        "code-sm": ["13px", { lineHeight: "20px", fontWeight: "400" }],
        "body-sm": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "display-hero-mobile": [
          "40px",
          { lineHeight: "48px", letterSpacing: "-0.02em", fontWeight: "700" },
        ],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "headline-lg": [
          "32px",
          { lineHeight: "40px", letterSpacing: "-0.02em", fontWeight: "600" },
        ],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "label-caps": [
          "12px",
          { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "600" },
        ],
        "display-hero": [
          "72px",
          { lineHeight: "80px", letterSpacing: "-0.04em", fontWeight: "700" },
        ],
      },
    },
  },
  plugins: [],
};
